### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Kapu141984** [brentvollebregt/mp3-iTunes#1]
I have selected

I am going to the browser version of iTunes and find the album your desired song.

e.g. https://itunes.apple.com/nz/album/wolves/id1227716339 and copy the url.

I am selecting this one

Then 

running 

Run spotify_album_downloader.py and insert the iTunes url and the number of the song in the album.

Now when i click om "Click get data" then that windows where we have inserted itunes URL get closes.

and i am get back to the command prompt

I am getting error as shown in attached pic

![error](https://user-images.githubusercontent.com/44629469/47765689-26bdc480-dcf1-11e8-970b-ad5f637bc7ac.png)

**Comment by brentvollebregt** [comment]
The iTunes in browser has a few more type="fastboot/shoebox" script elements so I just made it more focused to the id. Hopefully this will work for you.
